Traceback (most recent call last):
  File "/home/sasank/Documents/GitRepos/Stifle-Keypoints/scripts/etl.py", line 124, in <module>
    full_data = pd.read_csv(RAW_DATA_FILE)
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/sasank/miniconda3/envs/jtml/lib/python3.9/site-packages/pandas/io/common.py", line 427, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'int'>